// Generated by gencpp from file planner_manager/DVHcontrol.msg
// DO NOT EDIT!


#ifndef PLANNER_MANAGER_MESSAGE_DVHCONTROL_H
#define PLANNER_MANAGER_MESSAGE_DVHCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace planner_manager
{
template <class ContainerAllocator>
struct DVHcontrol_
{
  typedef DVHcontrol_<ContainerAllocator> Type;

  DVHcontrol_()
    : header()
    , left_wheel_vel(0.0)
    , right_wheel_vel(0.0)
    , vetical_vel(0.0)  {
    }
  DVHcontrol_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_wheel_vel(0.0)
    , right_wheel_vel(0.0)
    , vetical_vel(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _left_wheel_vel_type;
  _left_wheel_vel_type left_wheel_vel;

   typedef double _right_wheel_vel_type;
  _right_wheel_vel_type right_wheel_vel;

   typedef double _vetical_vel_type;
  _vetical_vel_type vetical_vel;





  typedef boost::shared_ptr< ::planner_manager::DVHcontrol_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_manager::DVHcontrol_<ContainerAllocator> const> ConstPtr;

}; // struct DVHcontrol_

typedef ::planner_manager::DVHcontrol_<std::allocator<void> > DVHcontrol;

typedef boost::shared_ptr< ::planner_manager::DVHcontrol > DVHcontrolPtr;
typedef boost::shared_ptr< ::planner_manager::DVHcontrol const> DVHcontrolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_manager::DVHcontrol_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_manager::DVHcontrol_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_manager::DVHcontrol_<ContainerAllocator1> & lhs, const ::planner_manager::DVHcontrol_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_wheel_vel == rhs.left_wheel_vel &&
    lhs.right_wheel_vel == rhs.right_wheel_vel &&
    lhs.vetical_vel == rhs.vetical_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_manager::DVHcontrol_<ContainerAllocator1> & lhs, const ::planner_manager::DVHcontrol_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner_manager::DVHcontrol_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_manager::DVHcontrol_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_manager::DVHcontrol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_manager::DVHcontrol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_manager::DVHcontrol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_manager::DVHcontrol_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_manager::DVHcontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c56293876f7e62ba1eb4b891f0f432e";
  }

  static const char* value(const ::planner_manager::DVHcontrol_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c56293876f7e62bULL;
  static const uint64_t static_value2 = 0xa1eb4b891f0f432eULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_manager::DVHcontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_manager/DVHcontrol";
  }

  static const char* value(const ::planner_manager::DVHcontrol_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_manager::DVHcontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"Header header\n"
"float64 left_wheel_vel\n"
"float64 right_wheel_vel\n"
"float64 vetical_vel\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::planner_manager::DVHcontrol_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_manager::DVHcontrol_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_wheel_vel);
      stream.next(m.right_wheel_vel);
      stream.next(m.vetical_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DVHcontrol_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_manager::DVHcontrol_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_manager::DVHcontrol_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_wheel_vel: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel_vel);
    s << indent << "right_wheel_vel: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel_vel);
    s << indent << "vetical_vel: ";
    Printer<double>::stream(s, indent + "  ", v.vetical_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MANAGER_MESSAGE_DVHCONTROL_H
