// Generated by gencpp from file quadrotor_msgs/LQRTrajectory.msg
// DO NOT EDIT!


#ifndef QUADROTOR_MSGS_MESSAGE_LQRTRAJECTORY_H
#define QUADROTOR_MSGS_MESSAGE_LQRTRAJECTORY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct LQRTrajectory_
{
  typedef LQRTrajectory_<ContainerAllocator> Type;

  LQRTrajectory_()
    : header()
    , trajectory_id(0)
    , action(0)
    , r(0.0)
    , start_yaw(0.0)
    , final_yaw(0.0)
    , s0()
    , ut()
    , sf()
    , t_f(0.0)
    , debug_info()  {
      s0.assign(0.0);

      ut.assign(0.0);

      sf.assign(0.0);
  }
  LQRTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , trajectory_id(0)
    , action(0)
    , r(0.0)
    , start_yaw(0.0)
    , final_yaw(0.0)
    , s0()
    , ut()
    , sf()
    , t_f(0.0)
    , debug_info(_alloc)  {
  (void)_alloc;
      s0.assign(0.0);

      ut.assign(0.0);

      sf.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _trajectory_id_type;
  _trajectory_id_type trajectory_id;

   typedef uint32_t _action_type;
  _action_type action;

   typedef double _r_type;
  _r_type r;

   typedef double _start_yaw_type;
  _start_yaw_type start_yaw;

   typedef double _final_yaw_type;
  _final_yaw_type final_yaw;

   typedef boost::array<double, 6>  _s0_type;
  _s0_type s0;

   typedef boost::array<double, 3>  _ut_type;
  _ut_type ut;

   typedef boost::array<double, 6>  _sf_type;
  _sf_type sf;

   typedef double _t_f_type;
  _t_f_type t_f;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _debug_info_type;
  _debug_info_type debug_info;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ACTION_ADD)
  #undef ACTION_ADD
#endif
#if defined(_WIN32) && defined(ACTION_ABORT)
  #undef ACTION_ABORT
#endif
#if defined(_WIN32) && defined(ACTION_WARN_START)
  #undef ACTION_WARN_START
#endif
#if defined(_WIN32) && defined(ACTION_WARN_FINAL)
  #undef ACTION_WARN_FINAL
#endif
#if defined(_WIN32) && defined(ACTION_WARN_IMPOSSIBLE)
  #undef ACTION_WARN_IMPOSSIBLE
#endif

  enum {
    ACTION_ADD = 1u,
    ACTION_ABORT = 2u,
    ACTION_WARN_START = 3u,
    ACTION_WARN_FINAL = 4u,
    ACTION_WARN_IMPOSSIBLE = 5u,
  };


  typedef boost::shared_ptr< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct LQRTrajectory_

typedef ::quadrotor_msgs::LQRTrajectory_<std::allocator<void> > LQRTrajectory;

typedef boost::shared_ptr< ::quadrotor_msgs::LQRTrajectory > LQRTrajectoryPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::LQRTrajectory const> LQRTrajectoryConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.trajectory_id == rhs.trajectory_id &&
    lhs.action == rhs.action &&
    lhs.r == rhs.r &&
    lhs.start_yaw == rhs.start_yaw &&
    lhs.final_yaw == rhs.final_yaw &&
    lhs.s0 == rhs.s0 &&
    lhs.ut == rhs.ut &&
    lhs.sf == rhs.sf &&
    lhs.t_f == rhs.t_f &&
    lhs.debug_info == rhs.debug_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator1> & lhs, const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46be446c56bc8bf131978edfc4464480";
  }

  static const char* value(const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46be446c56bc8bf1ULL;
  static const uint64_t static_value2 = 0x31978edfc4464480ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/LQRTrajectory";
  }

  static const char* value(const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# the trajectory id, starts from \"1\".\n"
"uint32 trajectory_id\n"
"\n"
"# the action command for trajectory server.\n"
"uint32 ACTION_ADD           =   1\n"
"uint32 ACTION_ABORT         =   2\n"
"uint32 ACTION_WARN_START           =   3\n"
"uint32 ACTION_WARN_FINAL           =   4\n"
"uint32 ACTION_WARN_IMPOSSIBLE      =   5\n"
"uint32 action\n"
"\n"
"# the weight coefficient of the control effort\n"
"float64 r\n"
"\n"
"# the yaw command\n"
"float64 start_yaw\n"
"float64 final_yaw\n"
"\n"
"# the initial and final state\n"
"float64[6] s0\n"
"float64[3] ut\n"
" \n"
"float64[6] sf \n"
"\n"
"# the optimal arrival time\n"
"float64 t_f\n"
"\n"
"string debug_info\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.trajectory_id);
      stream.next(m.action);
      stream.next(m.r);
      stream.next(m.start_yaw);
      stream.next(m.final_yaw);
      stream.next(m.s0);
      stream.next(m.ut);
      stream.next(m.sf);
      stream.next(m.t_f);
      stream.next(m.debug_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LQRTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quadrotor_msgs::LQRTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "trajectory_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.trajectory_id);
    s << indent << "action: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.action);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "start_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.start_yaw);
    s << indent << "final_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.final_yaw);
    s << indent << "s0[]" << std::endl;
    for (size_t i = 0; i < v.s0.size(); ++i)
    {
      s << indent << "  s0[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.s0[i]);
    }
    s << indent << "ut[]" << std::endl;
    for (size_t i = 0; i < v.ut.size(); ++i)
    {
      s << indent << "  ut[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ut[i]);
    }
    s << indent << "sf[]" << std::endl;
    for (size_t i = 0; i < v.sf.size(); ++i)
    {
      s << indent << "  sf[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.sf[i]);
    }
    s << indent << "t_f: ";
    Printer<double>::stream(s, indent + "  ", v.t_f);
    s << indent << "debug_info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.debug_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_LQRTRAJECTORY_H
